"""Centralized configuration constants for the hmem system."""

# Consolidator constants
CONSOLIDATOR_MAX_WORKERS = 2
CONSOLIDATOR_MAX_RETRIES = 3
CONSOLIDATOR_TIMEOUT = 30.0
CONSOLIDATOR_RETRY_DELAY = 1.0
CONSOLIDATOR_FORGETTING_THRESHOLD = 0.3
CONSOLIDATOR_DECAY_FACTOR = 0.99
CONSOLIDATOR_REFINEMENT_MIN_USAGE = 10
CONSOLIDATOR_REFINEMENT_MIN_SUCCESS_RATE = 0.5

# Memory system constants
MEMORY_SYSTEM_TIMEOUT = 30.0
MEMORY_SYSTEM_MAX_WORKERS = 4

# Ranking constants
# Updated to match interfaces.md HybridRankerWithExploration
RANKING_DEFAULT_SIMILARITY_WEIGHT = 0.4  # Primary signal (reduced from 0.5)
RANKING_DEFAULT_RECENCY_WEIGHT = 0.15
RANKING_DEFAULT_IMPORTANCE_WEIGHT = 0.15
RANKING_DEFAULT_OUTCOME_WEIGHT = 0.2  # Kept for backward compatibility
RANKING_DEFAULT_QUALITY_WEIGHT = 0.2  # Quality score from IndexProfile
RANKING_DEFAULT_EXPLORATION_WEIGHT = 0.1  # Exploration bonus for low-usage memories
RANKING_DEFAULT_IMPORTANCE_NORMALIZER = 100.0
RANKING_DEFAULT_RECENCY_HALFLIFE_DAYS = 30.0
RANKING_DEFAULT_SUCCESS_BOOST = 1.0
RANKING_DEFAULT_FAILURE_PENALTY = 0.3
RANKING_DEFAULT_INITIAL_EXPLORATION_RATE = 0.2
RANKING_DEFAULT_MIN_EXPLORATION_RATE = 0.05

# Embedding constants
EMBEDDING_DEFAULT_DIMENSION = 384
EMBEDDING_WORD_SCALE_FACTOR = 0.1

# Database constants
NEO4J_MAX_CONNECTION_RETRIES = 3
NEO4J_CONNECTION_RETRY_DELAY = 1.0

# Skill matching constants
SKILL_EXACT_MATCH_SCORE = 1.0
SKILL_SUBSTRING_MATCH_SCORE = 0.8
SKILL_DEFAULT_MATCH_THRESHOLD = 0.6
