from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


class Message(BaseModel):
    """Single message in a conversation (similar to OpenAI's message structure).
    
    This represents one turn in a conversation between user and assistant.
    Follows the OpenAI API message format for compatibility.
    """

    role: Literal["system", "user", "assistant"] = Field(
        description="Role of the message sender"
    )
    content: str = Field(description="Message content")
    timestamp: datetime = Field(
        default_factory=datetime.now, description="When the message was created"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Optional metadata (e.g., token_count, model)"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "role": "user",
                "content": "What's the weather like?",
                "timestamp": "2026-01-10T10:00:00",
                "metadata": {"token_count": 5},
            }
        }
    }


class Conversation(BaseModel):
    """A sequence of messages representing a conversation session.
    
    This is the primary input format for the memory system.
    """

    messages: list[Message] = Field(description="List of messages in chronological order")
    session_id: str = Field(description="Unique identifier for this conversation session")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Session-level metadata (e.g., user_id, topic)",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "session_id": "session_123",
                "messages": [
                    {"role": "user", "content": "My name is Alice"},
                    {"role": "assistant", "content": "Nice to meet you, Alice!"},
                ],
                "metadata": {"user_id": "user_001"},
            }
        }
    }


class Memory(BaseModel):
    """A retrieved memory from the system.
    
    This is what gets returned when recalling memories.
    Can represent different types: episodic (experiences), semantic (facts), or procedural (skills).
    """

    content: str = Field(description="The memory content")
    score: float = Field(ge=0, le=1, description="Relevance score")
    source: Literal["episodic", "semantic", "skill"] = Field(
        description="Source of the memory"
    )
    timestamp: datetime = Field(description="When this memory was created")
    metadata: dict[str, Any] = Field(default_factory=dict)

    model_config = {
        "json_schema_extra": {
            "example": {
                "content": "User prefers dark mode",
                "score": 0.95,
                "source": "semantic",
                "timestamp": "2026-01-10T10:00:00",
                "metadata": {"session_id": "s1"},
            }
        }
    }


class Event(BaseModel):
    """Episodic event - business layer data model.

    Note:
        - embedding/vector is auto-generated by storage layer, not part of business model
        - Use 'content' consistently instead of 'text' or 'raw_text'
    """

    content: str = Field(description="Text description of the event")
    outcome: Literal["success", "failure", "unknown"] = Field(
        description="Outcome of the event"
    )
    tags: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.now)
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Extended fields like session_id, user_query, etc.",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "content": "User asked to write a web scraper. Attempted using requests.get() but got blocked.",
                "outcome": "failure",
                "tags": ["web_scraping", "debugging"],
                "metadata": {"session_id": "s1", "user_query": "write a scraper"},
            }
        }
    }


class ConsolidationResult(BaseModel):
    """Consolidation result statistics."""

    success: bool
    stored_events: int
    updated_facts: int
    conflicts_resolved: int
    errors: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)

    model_config = {
        "json_schema_extra": {
            "example": {
                "success": True,
                "stored_events": 5,
                "updated_facts": 3,
                "conflicts_resolved": 1,
                "errors": [],
            }
        }
    }


class Principle(BaseModel):
    """Extracted principle."""

    content: str
    evidence_count: int = Field(
        description="Number of episodes supporting this principle"
    )
    confidence: float = Field(ge=0, le=1)
    created_at: datetime = Field(default_factory=datetime.now)
    metadata: dict[str, Any] = Field(default_factory=dict)

    model_config = {
        "json_schema_extra": {
            "example": {
                "content": "Data analysis tasks must start with data cleaning",
                "evidence_count": 5,
                "confidence": 0.85,
                "metadata": {"topic": "data_analysis"},
            }
        }
    }


class SemanticTriple(BaseModel):
    """Semantic triple."""

    subject: str
    predicate: str
    object: str
    weight: float = Field(default=1.0, ge=0)
    version: int = Field(default=1)
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)

    model_config = {
        "json_schema_extra": {
            "example": {
                "subject": "User",
                "predicate": "PREFERS",
                "object": "dark_mode",
                "weight": 1.0,
            }
        }
    }


class ReflectionContext(BaseModel):
    """Reflection context information."""

    episode_count: int
    time_span_days: float
    avg_similarity: float = Field(
        description="Average similarity of memories within topic"
    )
    last_reflection_time: datetime | None = None

    model_config = {
        "json_schema_extra": {
            "example": {
                "episode_count": 10,
                "time_span_days": 7.0,
                "avg_similarity": 0.8,
            }
        }
    }
