from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


class Message(BaseModel):
    """Single message in a conversation (similar to OpenAI's message structure).

    This represents one turn in a conversation between user and assistant.
    Follows the OpenAI API message format for compatibility.
    """

    role: Literal["system", "user", "assistant"] = Field(
        description="Role of the message sender"
    )
    content: str = Field(description="Message content")
    timestamp: datetime = Field(
        default_factory=datetime.now, description="When the message was created"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Optional metadata (e.g., token_count, model)"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "role": "user",
                "content": "What's the weather like?",
                "timestamp": "2026-01-10T10:00:00",
                "metadata": {"token_count": 5},
            }
        }
    }


class Conversation(BaseModel):
    """A sequence of messages representing a conversation session.

    This is the primary input format for the memory system.
    Conversations are at Level 0 (raw) in the hierarchical semantic graph
    and serve as the source for derived memories.
    """

    id: str | None = Field(
        default=None,
        description="Unique conversation identifier (auto-generated if not provided)",
    )
    messages: list[Message] = Field(
        description="List of messages in chronological order"
    )
    session_id: str = Field(
        description="Unique identifier for this conversation session"
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Session-level metadata (e.g., user_id, topic)",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "id": "conv_abc123",
                "session_id": "session_123",
                "messages": [
                    {"role": "user", "content": "My name is Alice"},
                    {"role": "assistant", "content": "Nice to meet you, Alice!"},
                ],
                "metadata": {"user_id": "user_001"},
            }
        }
    }


class Memory(BaseModel):
    """A retrieved memory from the system with provenance tracking.

    This is what gets returned when recalling memories.
    Can represent different types: episodic (experiences), semantic (facts), or procedural (skills).

    Provenance fields enable building a hierarchical semantic graph where:
    - Raw memories (conversations) are at Level 0
    - Episodic events are at Level 1 (derived from conversations)
    - Semantic facts are at Level 2 (derived from events)
    - Principles are at Level 3 (induced from multiple memories)
    """

    id: str | None = Field(default=None, description="Unique memory identifier")
    content: str = Field(description="The memory content")
    score: float = Field(ge=0, le=1, description="Relevance score")
    source: Literal["episodic", "semantic", "skill"] = Field(
        description="Source of the memory"
    )
    timestamp: datetime = Field(description="When this memory was created")
    metadata: dict[str, Any] = Field(default_factory=dict)
    parent_ids: list[str] = Field(
        default_factory=list,
        description="IDs of parent memories this was derived from",
    )
    derivation_type: (
        Literal["extraction", "derivation", "induction", "supersession"] | None
    ) = Field(
        default=None,
        description="How this memory was derived: extraction (from raw), derivation (from other memory), induction (from multiple memories), supersession (replacing old memory)",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "id": "mem_abc123",
                "content": "User prefers dark mode",
                "score": 0.95,
                "source": "semantic",
                "timestamp": "2026-01-10T10:00:00",
                "metadata": {"session_id": "s1"},
                "parent_ids": ["conv_xyz789"],
                "derivation_type": "extraction",
            }
        }
    }


class Event(BaseModel):
    """Episodic event - business layer data model with provenance tracking.

    Note:
        - embedding/vector is auto-generated by storage layer, not part of business model
        - Use 'content' consistently instead of 'text' or 'raw_text'

    Events are derived from raw conversations (Level 0) and form Level 1
    in the hierarchical semantic graph.
    """

    id: str | None = Field(default=None, description="Unique event identifier")
    content: str = Field(description="Text description of the event")
    outcome: Literal["success", "failure", "unknown"] = Field(
        description="Outcome of the event"
    )
    tags: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.now)
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Extended fields like session_id, user_query, etc.",
    )
    parent_ids: list[str] = Field(
        default_factory=list,
        description="IDs of source memories (e.g., conversation/message IDs)",
    )
    derivation_type: Literal["extraction", "derivation"] = Field(
        default="extraction",
        description="How this event was derived from parent memories",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "id": "evt_abc123",
                "content": "User asked to write a web scraper. Attempted using requests.get() but got blocked.",
                "outcome": "failure",
                "tags": ["web_scraping", "debugging"],
                "metadata": {"session_id": "s1", "user_query": "write a scraper"},
                "parent_ids": ["conv_xyz789"],
                "derivation_type": "extraction",
            }
        }
    }


class ConsolidationResult(BaseModel):
    """Consolidation result statistics."""

    success: bool
    stored_events: int
    updated_facts: int
    conflicts_resolved: int
    errors: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)

    model_config = {
        "json_schema_extra": {
            "example": {
                "success": True,
                "stored_events": 5,
                "updated_facts": 3,
                "conflicts_resolved": 1,
                "errors": [],
            }
        }
    }


class Principle(BaseModel):
    """Extracted principle with multi-evidence provenance.

    Principles are at Level 3 in the hierarchical semantic graph,
    induced from multiple Level 1/2 memories (events/facts).
    """

    id: str | None = Field(default=None, description="Unique principle identifier")
    content: str
    evidence_count: int = Field(
        description="Number of episodes supporting this principle"
    )
    confidence: float = Field(ge=0, le=1)
    created_at: datetime = Field(default_factory=datetime.now)
    metadata: dict[str, Any] = Field(default_factory=dict)
    parent_ids: list[str] = Field(
        default_factory=list,
        description="IDs of evidence memories this principle was induced from",
    )
    derivation_type: Literal["induction"] = Field(
        default="induction",
        description="Principles are always induced from multiple memories",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "id": "prin_abc123",
                "content": "Data analysis tasks must start with data cleaning",
                "evidence_count": 5,
                "confidence": 0.85,
                "metadata": {"topic": "data_analysis"},
                "parent_ids": ["evt_001", "evt_002", "evt_003"],
                "derivation_type": "induction",
            }
        }
    }


class SemanticTriple(BaseModel):
    """Semantic triple with provenance tracking.

    Semantic triples are at Level 2 in the hierarchical semantic graph,
    derived from events or conversations.
    """

    id: str | None = Field(default=None, description="Unique triple identifier")
    subject: str
    predicate: str
    object: str
    weight: float = Field(default=1.0, ge=0)
    version: int = Field(default=1)
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)
    parent_ids: list[str] = Field(
        default_factory=list,
        description="IDs of source memories this fact was derived from",
    )
    derivation_type: Literal["extraction", "derivation", "supersession"] = Field(
        default="extraction",
        description="How this triple was derived",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "id": "triple_abc123",
                "subject": "User",
                "predicate": "PREFERS",
                "object": "dark_mode",
                "weight": 1.0,
                "parent_ids": ["conv_xyz789"],
                "derivation_type": "extraction",
            }
        }
    }


class ReflectionContext(BaseModel):
    """Reflection context information."""

    episode_count: int
    time_span_days: float
    avg_similarity: float = Field(
        description="Average similarity of memories within topic"
    )
    last_reflection_time: datetime | None = None

    model_config = {
        "json_schema_extra": {
            "example": {
                "episode_count": 10,
                "time_span_days": 7.0,
                "avg_similarity": 0.8,
            }
        }
    }
