from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Memory(BaseModel):
    content: str
    score: float = Field(ge=0, le=1, description="Relevance score")
    source: str = Field(description="Source: episodic/semantic/skill")
    timestamp: datetime
    metadata: Dict[str, Any] = Field(default_factory=dict)

    model_config = {
        "json_schema_extra": {
            "example": {
                "content": "User prefers dark mode",
                "score": 0.95,
                "source": "semantic",
                "timestamp": "2026-01-10T10:00:00",
                "metadata": {"session_id": "s1"},
            }
        }
    }


class Event(BaseModel):
    """Episodic event - business layer data model.

    Note:
        - embedding/vector is auto-generated by storage layer, not part of business model
        - Use 'content' consistently instead of 'text' or 'raw_text'
    """

    content: str = Field(description="Text description of the event")
    outcome: str = Field(description="success/failure/unknown")
    tags: List[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.now)
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Extended fields like session_id, user_query, etc.",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "content": "User asked to write a web scraper. Attempted using requests.get() but got blocked.",
                "outcome": "failure",
                "tags": ["web_scraping", "debugging"],
                "metadata": {"session_id": "s1", "user_query": "write a scraper"},
            }
        }
    }


class ConsolidationResult(BaseModel):
    """Consolidation result statistics."""

    success: bool
    stored_events: int
    updated_facts: int
    conflicts_resolved: int
    errors: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    model_config = {
        "json_schema_extra": {
            "example": {
                "success": True,
                "stored_events": 5,
                "updated_facts": 3,
                "conflicts_resolved": 1,
                "errors": [],
            }
        }
    }


class Principle(BaseModel):
    """Extracted principle."""

    content: str
    evidence_count: int = Field(
        description="Number of episodes supporting this principle"
    )
    confidence: float = Field(ge=0, le=1)
    created_at: datetime = Field(default_factory=datetime.now)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    model_config = {
        "json_schema_extra": {
            "example": {
                "content": "Data analysis tasks must start with data cleaning",
                "evidence_count": 5,
                "confidence": 0.85,
                "metadata": {"topic": "data_analysis"},
            }
        }
    }


class SemanticTriple(BaseModel):
    """Semantic triple."""

    subject: str
    predicate: str
    object: str
    weight: float = Field(default=1.0, ge=0)
    version: int = Field(default=1)
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)

    model_config = {
        "json_schema_extra": {
            "example": {
                "subject": "User",
                "predicate": "PREFERS",
                "object": "dark_mode",
                "weight": 1.0,
            }
        }
    }


class ReflectionContext(BaseModel):
    """Reflection context information."""

    episode_count: int
    time_span_days: float
    avg_similarity: float = Field(
        description="Average similarity of memories within topic"
    )
    last_reflection_time: Optional[datetime] = None

    model_config = {
        "json_schema_extra": {
            "example": {
                "episode_count": 10,
                "time_span_days": 7.0,
                "avg_similarity": 0.8,
            }
        }
    }
